<a href="https://colab.research.google.com/github/abdallahlakh/Scraper/blob/main/fds_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the packages

In [3]:
import numpy as np

Array Creation and Manipulation:


1:

In [4]:
array = np.arange(10)

In [5]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2:

In [9]:
array_2d=np.zeros((3,4))

In [10]:
array_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

3:

In [15]:
array_spaced = np.linspace(0, 1, 10)

In [16]:
array_spaced

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

4:

In [17]:
random_matrix = np.random.rand(3, 3)


In [18]:
random_matrix

array([[0.86307233, 0.53935697, 0.31605201],
       [0.01581198, 0.50174616, 0.93847589],
       [0.43805035, 0.01058836, 0.79932796]])

5:

In [23]:
t=np.asarray([x for x in range(10,51) if x % 2 ==0])

In [24]:
t

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

6:

In [30]:

identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7:

In [32]:
array_log_spaced = np.logspace(0, 2, 20,base=10)
array_log_spaced

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

8:

In [47]:
original_array = np.arange(10)
original_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

9:

In [50]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
original_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

10:

In [51]:
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd_numbers = original_array[original_array % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])